"""added unique consraint into likes model

Revision ID: f8a7677166ae
Revises: a705d6d7a4d2
Create Date: 2026-02-22 17:21:31.859617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a7677166ae'
down_revision: Union[str, None] = 'a705d6d7a4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_post_user', 'likes', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_user', 'likes', type_='unique')
    # ### end Alembic commands ###
