name: mini-social-api

services:
  users_db:
    container_name: users_db
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mini-social-network

networks:
  mini-social-network:
    driver: bridge